import assert from 'node:assert/strict'
import { mkdir } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { resolve } from 'node:path'
import { _electron as electron } from 'playwright'

const appRoot = resolve(fileURLToPath(new URL('../', import.meta.url)))
const output = fileURLToPath(new URL('../out/smoke/', import.meta.url))
await mkdir(output, { recursive: true })
const env = { ...process.env }
delete env['ELECTRON_RUN_AS_NODE']
delete env['ELECTRON_RENDERER_URL']
const app = await electron.launch({ args: [appRoot], env })
const failures = []
try {
  const page = await app.firstWindow()
  page.on('pageerror', error => failures.push(error.message))
  page.on('console', message => { if (message.type() === 'error') failures.push(message.text()) })
  await page.waitForLoadState('domcontentloaded')
  await page.evaluate(() => {
    const proto = CanvasRenderingContext2D.prototype
    const transform = proto.setTransform
    const text = proto.fillText
    window.__drawnText = []
    proto.setTransform = function (...args) { window.__drawnText = []; return transform.apply(this, args) }
    proto.fillText = function (...args) { window.__drawnText.push(args[0]); return text.apply(this, args) }
  })
  await page.waitForFunction(() => window.__ledmap && window.__ledmap.dump().length === 3)

  const dump = async () => page.evaluate(() => window.__ledmap.dump())
  const selection = async () => page.evaluate(() => window.__ledmap.selection())
  const bounds = async () => page.evaluate(() => window.__ledmap.bounds())
  const viewMode = async () => page.evaluate(() => window.__ledmap.viewMode())
  const camera = async () => page.evaluate(() => window.__ledmap.camera())
  const canvasBox = async () => (await page.locator('#project-canvas').boundingBox())

  const initial = await dump()
  assert.equal(initial.length, 3)
  assert.deepEqual(initial.map(s => s.name), ['Screen 1', 'Screen 2', 'Screen 3'])
  assert.deepEqual(initial.map(s => [s.x, s.y]), [[0, 0], [700, 120], [320, 620]])
  assert.ok((await bounds()).width === 1084 && (await bounds()).height === 876)
  assert.match(await page.locator('#bounds').innerText(), /Project bounds 1,084 × 876 px/)
  assert.equal(initial[0].cabinets.length, 12)
  assert.deepEqual(initial[0].order, [1, 2, 3, 4, 8, 7, 6, 5, 9, 10, 11, 12])
  assert.deepEqual(initial[0].cabinets.map(c => c.id), Array.from({ length: 12 }, (_, i) => `C${String(i + 1).padStart(2, '0')}`))
  assert.deepEqual(initial[1].order, [1, 2, 3, 6, 5, 4])
  assert.deepEqual(initial[2].order, [1, 2, 3, 4, 8, 7, 6, 5])
  assert.match(await page.locator('#project-tree').innerText(), /Screens \(3\)/)
  assert.match(await page.locator('#project-canvas').getAttribute('aria-label'), /3 screens/)

  await page.locator('#project-tree [role="treeitem"]').filter({ hasText: 'Screen 1' }).click()
  assert.equal((await selection())?.type, 'screen')
  assert.equal((await selection())?.id, 'screen-1')
  assert.equal(await page.locator('#properties-title').innerText(), 'Screen')
  assert.equal(await page.locator('#selection-chip').innerText(), 'Screen 1 selected')
  assert.equal(await page.locator('input[aria-label="Screen X position"]').inputValue(), '0')

  const xInput = page.locator('input[aria-label="Screen X position"]')
  await xInput.fill('120')
  await xInput.blur()
  assert.equal((await dump())[0].x, 120)
  assert.equal((await dump())[0].y, 0)
  assert.equal(await page.locator('input[aria-label="Screen X position"]').inputValue(), '120')
  assert.equal((await bounds()).width, 964)

  await page.evaluate(() => {
    const input = document.querySelector('input[aria-label="Screen X position"]')
    input.value = ''
    input.dispatchEvent(new Event('change', { bubbles: true }))
  })
  await page.waitForFunction(() => document.querySelector('input[aria-label="Screen X position"]').getAttribute('aria-invalid') === 'true')
  assert.equal((await dump())[0].x, 120)

  await page.locator('#project-tree [role="treeitem"]').filter({ hasText: 'Cabinet Grid' }).first().click()
  assert.equal((await selection())?.type, 'cabinetGrid')
  assert.equal(await page.locator('#properties-title').innerText(), 'Cabinet Grid')
  const gridColumnsInput = page.locator('input[aria-label="Cabinet Grid Columns"]')
  const gridRowsInput = page.locator('input[aria-label="Cabinet Grid Rows"]')
  assert.equal(await gridColumnsInput.inputValue(), '4')
  assert.equal(await gridRowsInput.inputValue(), '3')
  await gridColumnsInput.fill('5')
  await gridColumnsInput.blur()
  assert.equal((await dump())[0].columns, 5)
  assert.equal((await dump())[0].cabinets.length, 15)
  assert.equal((await selection())?.type, 'cabinetGrid', 'grid selection survives resize commit')
  assert.equal((await dump())[1].columns, 3, 'grid edit only changes the owning screen')
  await gridColumnsInput.fill('4')
  await gridColumnsInput.blur()
  assert.equal((await dump())[0].columns, 4)
  assert.equal((await dump())[0].rows, 3)
  assert.equal((await dump())[0].cabinets.length, 12)

  await gridColumnsInput.fill('400')
  await gridColumnsInput.blur()
  await page.waitForFunction(() => document.querySelector('input[aria-label="Cabinet Grid Columns"]').getAttribute('aria-invalid') === 'true')
  assert.equal((await dump())[0].columns, 4, 'value above the limit does not mutate the model')
  assert.equal(await gridColumnsInput.inputValue(), '4')
  assert.match(await gridColumnsInput.getAttribute('title'), /limited to 341/)
  assert.equal((await selection())?.type, 'cabinetGrid')

  await page.locator('#toggle-mode').click()
  assert.equal(await viewMode(), 'active')
  assert.equal(await page.locator('#toggle-mode').innerText(), 'All Screens')
  assert.equal(await page.locator('#canvas-title').innerText(), 'Screen 1')
  await page.waitForFunction(() => window.__drawnText.some(t => /^C\d\d$/.test(t)))
  assert.deepEqual(await page.evaluate(() => window.__drawnText.filter(t => t.startsWith('#'))), [])
  assert.deepEqual(
    await page.evaluate(() => [...new Set(window.__drawnText.filter(t => /^C\d\d$/.test(t)))].sort()),
    Array.from({ length: 12 }, (_, i) => `C${String(i + 1).padStart(2, '0')}`),
  )

  const box = await canvasBox()
  assert.ok(box)
  const cabinetPoint = await page.evaluate(() => window.__ledmap.projectToPx({ x: 120 + 64, y: 0 + 64 }))
  await page.mouse.click(box.x + cabinetPoint.x, box.y + cabinetPoint.y)
  assert.equal((await selection())?.type, 'cabinet')
  assert.equal((await selection()).screenId, 'screen-1')
  assert.equal(await page.locator('#properties-title').innerText(), 'Cabinet')
  assert.match(await page.locator('#properties').innerText(), /Physical ID\s*C01/)

  const center = await page.evaluate(() => window.__ledmap.screenCenterPx('screen-1'))
  const zoomBefore = (await camera()).zoom
  const beforeBounds = await bounds()
  const beforeDrag = await dump()
  await page.locator('#snap-toggle').click()
  assert.equal(await page.locator('#snap-state').innerText(), 'Snap off')
  await page.mouse.move(box.x + center.x, box.y + center.y)
  await page.mouse.down()
  await page.mouse.move(box.x + center.x + 40, box.y + center.y + 20, { steps: 6 })
  await page.mouse.up()
  const afterDrag = await dump()
  const movedBy = { x: afterDrag[0].x - beforeDrag[0].x, y: afterDrag[0].y - beforeDrag[0].y }
  assert.ok(Math.abs(movedBy.x - 40 / zoomBefore) < 0.6, `expected dx≈${40 / zoomBefore}, got ${movedBy.x}`)
  assert.ok(Math.abs(movedBy.y - 20 / zoomBefore) < 0.6, `expected dy≈${20 / zoomBefore}, got ${movedBy.y}`)
  assert.equal((await selection())?.type, 'screen')
  assert.deepEqual(afterDrag[0].order, [1, 2, 3, 4, 8, 7, 6, 5, 9, 10, 11, 12])
  assert.deepEqual(afterDrag[0].cabinets.map(c => c.id), beforeDrag[0].cabinets.map(c => c.id))
  const movedBounds = await bounds()
  assert.ok(movedBounds.width < beforeBounds.width, 'bounds width recalculates after drag')
  assert.ok(movedBounds.height < beforeBounds.height, 'bounds height recalculates after drag')
  assert.ok(movedBounds.left > beforeBounds.left && movedBounds.top > beforeBounds.top, 'bounds origin follows the moved screen')
  await page.locator('#snap-toggle').click()
  assert.equal(await page.locator('#snap-state').innerText(), 'Snap on: Grid+Edges+Centers+Guides')

  await page.locator('#toggle-mode').click()
  assert.equal(await viewMode(), 'all')
  assert.equal(await page.locator('#toggle-mode').innerText(), 'Active Screen')

  await page.locator('#add-screen').click()
  const afterAdd = await dump()
  assert.equal(afterAdd.length, 4)
  assert.equal(afterAdd[3].name, 'Screen 4')
  assert.equal(afterAdd[3].x, 420)
  assert.equal(afterAdd[3].y, 720)
  assert.equal((await selection())?.id, 'screen-4')

  await page.keyboard.press('Escape')
  assert.equal(await selection(), null)
  assert.equal(await page.locator('#selection-chip').innerText(), 'No selection')

  await page.locator('#project-tree [role="treeitem"]').filter({ hasText: 'Screen 3' }).click()
  assert.equal(await page.locator('#properties-title').innerText(), 'Screen')
  assert.equal(await page.locator('input[aria-label="Screen Y position"]').inputValue(), '620')

  const preview = async () => page.evaluate(() => window.__ledmap.preview())
  const handles = async id => page.evaluate(screenId => window.__ledmap.resizeHandlesPx(screenId), id)
  const drawnText = async () => page.evaluate(() => window.__drawnText)
  const screen3Before = (await dump())[2]
  const boundsBeforeResize = await bounds()

  const columnsInput = page.locator('input[aria-label="Screen Columns"]')
  const rowsInput = page.locator('input[aria-label="Screen Rows"]')
  assert.equal(await columnsInput.inputValue(), '4')
  assert.equal(await rowsInput.inputValue(), '2')
  assert.match(await page.locator('#properties').innerText(), /Calculated Screen Size\s*Width\s*512 px\s*Height\s*256 px/)
  assert.match(await page.locator('#properties').innerText(), /Cabinet\s*Width\s*128 px\s*Height\s*128 px/)
  assert.equal(await page.locator('#properties').innerText().then(text => /128 px[\s\S]*128 px/.test(text)), true)

  await columnsInput.fill('6')
  await columnsInput.blur()
  const grown = (await dump())[2]
  assert.equal(grown.columns, 6)
  assert.equal(grown.width, 768)
  assert.equal(grown.height, 256)
  assert.equal(grown.cabinets.length, 12)
  assert.deepEqual(grown.cabinets.filter(c => c.column < 4).map(c => c.id), screen3Before.cabinets.map(c => c.id))
  assert.deepEqual(grown.order, [1, 2, 3, 4, 5, 6, 12, 11, 10, 9, 8, 7])
  assert.ok((await bounds()).width > boundsBeforeResize.width, 'project bounds grow with the resized screen')
  assert.equal((await dump())[0].columns, 4, 'other screens are untouched')
  assert.equal((await dump())[1].columns, 3, 'other screens are untouched')
  assert.equal(await preview(), null, 'properties commit does not leave a preview')
  assert.equal(await page.locator('input[aria-label="Screen Columns"]').inputValue(), '6')

  await columnsInput.fill('0')
  await columnsInput.blur()
  await page.waitForFunction(() => document.querySelector('input[aria-label="Screen Columns"]').getAttribute('aria-invalid') === 'true')
  assert.equal((await dump())[2].columns, 6, 'invalid value does not mutate the model')
  assert.equal(await page.locator('input[aria-label="Screen Columns"]').inputValue(), '6')

  await rowsInput.fill('4')
  await rowsInput.blur()
  assert.equal((await dump())[2].rows, 4)
  assert.equal((await dump())[2].height, 512)
  const grownCells = (await dump())[2].cabinets.map(c => `${c.column},${c.row}:${c.id}`)

  await page.locator('#toggle-mode').click()
  await page.locator('#fit-project').click()
  assert.equal(await viewMode(), 'active')
  let step = 2 * 128 * (await camera()).zoom
  const cornerOf = async () => (await handles('screen-3')).find(h => h.handle === 'bottomRight')
  const handleList = await handles('screen-3')
  assert.deepEqual(handleList.map(h => h.handle).sort(), ['bottom', 'bottomRight', 'right'])
  let corner = await cornerOf()

  await page.mouse.move(box.x + corner.x, box.y + corner.y)
  assert.equal(await page.locator('#project-canvas').evaluate(node => node.style.cursor), 'se-resize')
  await page.mouse.down()
  assert.equal(await preview(), null, 'gesture captures the original size without a preview')
  assert.equal((await dump())[2].columns, 6)
  assert.equal((await dump())[2].rows, 4)

  await page.mouse.move(box.x + corner.x + step, box.y + corner.y + step, { steps: 4 })
  assert.deepEqual(await preview(), { screenId: 'screen-3', columns: 8, rows: 6 })
  assert.equal((await dump())[2].columns, 6, 'preview does not mutate the project')
  assert.equal((await dump())[2].rows, 4)
  assert.equal((await dump())[2].x, grown.x, 'handle drag does not move the screen')
  assert.equal((await dump())[2].y, grown.y)
  const previewLabels = (await drawnText()).filter(t => /^C\d\d$/.test(t))
  assert.deepEqual(
    [...new Set(previewLabels)].sort(),
    [...new Set(grownCells.map(cell => cell.split(':')[1]))].sort(),
    'pending preview cells are drawn without IDs, numbers or new identity',
  )
  assert.equal(previewLabels.length, grownCells.length, 'each existing cabinet keeps exactly one label')
  assert.ok((await drawnText()).some(t => t.includes('8 × 6 cabinets') && t.includes('preview')))
  await page.screenshot({ path: `${output}/resize-preview.png` })

  await page.mouse.move(box.x + corner.x + 2 * step, box.y + corner.y + 2 * step, { steps: 4 })
  assert.deepEqual(await preview(), { screenId: 'screen-3', columns: 10, rows: 8 })
  await page.mouse.move(box.x + corner.x + step, box.y + corner.y + step, { steps: 4 })
  assert.deepEqual(await preview(), { screenId: 'screen-3', columns: 8, rows: 6 })
  await page.mouse.up()
  assert.equal(await preview(), null, 'gesture ends without a preview')
  const committed = (await dump())[2]
  assert.equal(committed.columns, 8)
  assert.equal(committed.rows, 6)
  assert.equal(committed.width, 1024)
  assert.equal(committed.height, 768)
  assert.equal(committed.cabinets.length, 48)
  const committedCells = new Map(committed.cabinets.map(c => [`${c.column},${c.row}`, c.id]))
  assert.ok(
    grownCells.every(cell => committedCells.get(cell.slice(0, cell.indexOf(':'))) === cell.slice(cell.indexOf(':') + 1)),
    'every existing cabinet keeps identity and position',
  )
  assert.equal(new Set(committed.cabinets.map(c => c.id)).size, 48, 'IDs are never reused')
  assert.equal(committed.cabinets.filter(c => !grownCells.some(cell => cell.endsWith(`:${c.id}`))).length, 24)
  assert.deepEqual([...committed.order].sort((a, b) => a - b), [...Array(48).keys()].map(i => i + 1))
  assert.equal((await selection())?.type, 'screen')
  assert.equal((await selection())?.id, 'screen-3')

  await page.locator('#fit-project').click()
  step = 2 * 128 * (await camera()).zoom
  corner = await cornerOf()
  await page.mouse.move(box.x + corner.x, box.y + corner.y)
  await page.mouse.down()
  await page.mouse.move(box.x + corner.x - step, box.y + corner.y, { steps: 4 })
  assert.deepEqual(await preview(), { screenId: 'screen-3', columns: 6, rows: 6 })
  await page.keyboard.press('Escape')
  assert.equal(await preview(), null)
  await page.mouse.up()
  assert.equal((await dump())[2].columns, 8, 'Escape cancels the gesture without a commit')
  assert.equal((await dump())[2].rows, 6)
  assert.equal((await selection()), null)

  await page.locator('#toggle-mode').click()
  await page.locator('#fit-project').click()
  assert.equal(await viewMode(), 'all')

  await page.locator('#project-tree [role="treeitem"]').filter({ hasText: 'Screen 1' }).click()
  assert.equal(await page.locator('#properties-title').innerText(), 'Screen')
  const refIds = Array.from({ length: 12 }, (_, i) => `C${String(i + 1).padStart(2, '0')}`)
  assert.equal(await page.locator('select[aria-label="Screen Numbering"]').count(), 0)
  assert.equal(await page.locator('select[aria-label="Screen Direction"]').count(), 0)
  assert.equal(await page.locator('input[aria-label="Screen Snake"]').count(), 0)
  assert.ok(!/Numbering|Direction|Snake|Logical order|Signal/.test(await page.locator('#properties').innerText()))
  assert.deepEqual((await dump())[0].order, [1, 2, 3, 4, 8, 7, 6, 5, 9, 10, 11, 12])
  assert.deepEqual((await dump())[0].cabinets.map(c => c.id), refIds)
  assert.deepEqual(await page.evaluate(() => window.__drawnText.filter(t => t.startsWith('#'))), [])
  assert.equal(await page.locator('.tree-panel h1').innerText(), 'Composition')
  assert.match(await page.locator('.preview-heading .eyebrow').innerText(), /COMPOSITION WORKSPACE/)

  const selectionSet = async () => page.evaluate(() => window.__ledmap.selectionSet())
  const byName = async name => (await dump()).find(s => s.name === name)

  await page.locator('#project-tree [role="treeitem"]').filter({ hasText: 'Screen 1' }).click()
  await page.locator('#project-tree [role="treeitem"]').filter({ hasText: 'Screen 2' }).click({ modifiers: ['Control'] })
  let set = await selectionSet()
  assert.deepEqual(set.items.map(i => i.id), ['screen-1', 'screen-2'])
  assert.equal(set.primary.id, 'screen-2')
  assert.equal(await page.locator('#selection-chip').innerText(), '2 Screens selected')
  assert.equal(await page.locator('#properties-title').innerText(), '2 Screens')

  const pairBefore = await dump()
  const pairCenter = await page.evaluate(() => window.__ledmap.screenCenterPx('screen-1'))
  await page.mouse.move(box.x + pairCenter.x, box.y + pairCenter.y)
  await page.mouse.down()
  await page.mouse.move(box.x + pairCenter.x + 30, box.y + pairCenter.y + 10, { steps: 5 })
  await page.mouse.up()
  const pairAfter = await dump()
  const deltaA = { x: pairAfter[0].x - pairBefore[0].x, y: pairAfter[0].y - pairBefore[0].y }
  const deltaB = { x: pairAfter[1].x - pairBefore[1].x, y: pairAfter[1].y - pairBefore[1].y }
  assert.ok(Math.abs(deltaA.x) > 1)
  assert.ok(Math.abs(deltaA.x - deltaB.x) < 1e-9 && Math.abs(deltaA.y - deltaB.y) < 1e-9)
  set = await selectionSet()
  assert.deepEqual(set.items.map(i => i.id), ['screen-1', 'screen-2'])

  const cornerA = await page.evaluate(() => window.__ledmap.projectToPx({ x: 300, y: 600 }))
  const cornerB = await page.evaluate(() => window.__ledmap.projectToPx({ x: 1400, y: 1400 }))
  await page.mouse.move(box.x + cornerA.x, box.y + cornerA.y)
  await page.mouse.down()
  await page.mouse.move(box.x + cornerB.x, box.y + cornerB.y, { steps: 5 })
  assert.notEqual(await page.evaluate(() => window.__ledmap.boxPreview()), null)
  await page.mouse.up()
  assert.equal(await page.evaluate(() => window.__ledmap.boxPreview()), null)
  set = await selectionSet()
  assert.deepEqual(set.items.map(i => i.id), ['screen-3', 'screen-4'])
  assert.equal(set.primary.id, 'screen-4')

  await page.keyboard.down('Control')
  await page.mouse.move(box.x + cornerA.x, box.y + cornerA.y)
  await page.mouse.down()
  await page.mouse.move(box.x + cornerB.x, box.y + cornerB.y, { steps: 5 })
  await page.mouse.up()
  await page.keyboard.up('Control')
  set = await selectionSet()
  assert.deepEqual(set.items.map(i => i.id), ['screen-3', 'screen-4'])
  assert.equal(set.primary.id, 'screen-4', 'Ctrl+box with zero new candidates preserves primary')

  const quadBefore = await dump()
  await page.keyboard.press('Control+d')
  const quadAfter = await dump()
  assert.equal(quadAfter.length, quadBefore.length + 2)
  assert.deepEqual(quadAfter.slice(-2).map(s => s.id), ['screen-5', 'screen-6'])
  assert.deepEqual(quadAfter.slice(-2).map(s => s.name), ['Screen 3 copy', 'Screen 4 copy'])
  assert.equal(quadAfter[4].columns, quadBefore[2].columns)
  assert.equal(quadAfter[4].cabinets.length, quadBefore[2].cabinets.length)
  assert.deepEqual(
    (await byName('Screen 3 copy')).cabinets.map(c => c.id),
    Array.from({ length: 48 }, (_, i) => `C${String(i + 1).padStart(2, '0')}`),
    'duplicate allocates a fresh cabinet namespace in the new screen',
  )
  assert.equal(quadAfter[4].x, quadBefore[2].x + 32)
  assert.equal(quadAfter[4].y, quadBefore[2].y + 32)
  set = await selectionSet()
  assert.deepEqual(set.items.map(i => i.id), ['screen-5', 'screen-6'])
  assert.equal(set.primary.id, 'screen-6')

  await page.locator('#project-tree [role="treeitem"]').filter({ hasText: 'Screen 3 copy' }).click()
  await page.locator('input[aria-label="Screen Locked"]').check()
  assert.equal((await byName('Screen 3 copy')).locked, true)
  await page.locator('#project-tree [role="treeitem"]').filter({ hasText: 'Screen 4 copy' }).click({ modifiers: ['Control'] })
  const lockedMix = await dump()
  const lockedCenter = await page.evaluate(() => window.__ledmap.screenCenterPx('screen-6'))
  await page.mouse.move(box.x + lockedCenter.x, box.y + lockedCenter.y)
  await page.mouse.down()
  await page.mouse.move(box.x + lockedCenter.x + 30, box.y + lockedCenter.y, { steps: 3 })
  await page.mouse.up()
  assert.deepEqual(await dump(), lockedMix, 'drag of a mixed locked selection changes nothing')
  await page.keyboard.press('ArrowRight')
  assert.deepEqual(await dump(), lockedMix, 'nudge of a mixed locked selection changes nothing')
  await page.keyboard.press('Delete')
  assert.equal((await dump()).length, lockedMix.length, 'delete of a mixed locked selection is blocked')
  set = await selectionSet()
  assert.deepEqual(set.items.map(i => i.id), ['screen-5', 'screen-6'])

  await page.keyboard.press('Control+d')
  const unlockedCopies = await dump()
  assert.equal(unlockedCopies.length, lockedMix.length + 2)
  assert.equal(unlockedCopies[6].locked, false)
  assert.equal(unlockedCopies[7].locked, false)
  await page.keyboard.press('Delete')
  assert.equal((await dump()).length, lockedMix.length)

  await page.locator('#project-tree [role="treeitem"]').filter({ hasText: 'Screen 3 copy' }).click()
  await page.locator('input[aria-label="Screen Locked"]').uncheck()
  await page.locator('#project-tree [role="treeitem"]').filter({ hasText: 'Screen 4 copy' }).click({ modifiers: ['Control'] })
  await page.keyboard.press('Delete')
  const afterDelete = await dump()
  assert.deepEqual(afterDelete.map(s => s.id), ['screen-1', 'screen-2', 'screen-3', 'screen-4'])
  assert.equal((await selectionSet()).items.length, 0)
  assert.equal(await page.locator('#selection-chip').innerText(), 'No selection')

  await page.locator('#project-tree [role="treeitem"]').filter({ hasText: 'Screen 1' }).click()
  await page.locator('input[aria-label="Screen X position"]').click()
  const guardBefore = await dump()
  await page.keyboard.press('ArrowRight')
  assert.deepEqual(await dump(), guardBefore, 'property-control focus prevents nudge')
  await page.keyboard.press('Escape')
  assert.equal((await selection()).id, 'screen-1', 'Escape from a property control blurs instead of clearing')
  await page.keyboard.press('Escape')
  assert.equal(await selection(), null)
  await page.locator('#project-tree [role="treeitem"]').filter({ hasText: 'Screen 1' }).click()
  await page.mouse.click(box.x + 10, box.y + 10)
  assert.equal(await selection(), null, 'empty canvas click clears the selection')

  await page.locator('#project-tree [role="treeitem"]').filter({ hasText: 'Screen 4' }).click()
  await page.keyboard.press('Delete')
  assert.deepEqual((await dump()).map(s => s.id), ['screen-1', 'screen-2', 'screen-3'])
  await page.locator('#add-screen').click()
  const readded = await dump()
  assert.equal(readded.length, 4)
  assert.equal(new Set(readded.map(s => s.id)).size, 4, 'add after deleting the highest ID collides with nothing live')
  assert.equal(readded[3].name, 'Screen 4')

  const guidesOf = async () => page.evaluate(() => window.__ledmap.guides())
  const gridMultiple = value => Math.abs(value / 8 - Math.round(value / 8)) < 1e-9

  await page.locator('#snap-edges').click()
  await page.locator('#snap-centers').click()
  await page.locator('#snap-guides').click()
  assert.equal(await page.locator('#snap-state').innerText(), 'Snap on: Grid')
  await page.locator('#project-tree [role="treeitem"]').filter({ hasText: 'Screen 1' }).click()
  const snapCenter = await page.evaluate(() => window.__ledmap.screenCenterPx('screen-1'))
  await page.mouse.move(box.x + snapCenter.x, box.y + snapCenter.y)
  await page.mouse.down()
  await page.mouse.move(box.x + snapCenter.x + 37, box.y + snapCenter.y + 13, { steps: 5 })
  await page.mouse.up()
  const snapAfter = await dump()
  assert.ok(gridMultiple(snapAfter[0].x) && gridMultiple(snapAfter[0].y))

  await page.locator('#project-tree [role="treeitem"]').filter({ hasText: 'Screen 2' }).click({ modifiers: ['Control'] })
  const altZoom = (await camera()).zoom
  const altBefore = await dump()
  await page.keyboard.down('Alt')
  await page.mouse.move(box.x + snapCenter.x, box.y + snapCenter.y)
  await page.mouse.down()
  await page.mouse.move(box.x + snapCenter.x + 37, box.y + snapCenter.y, { steps: 5 })
  await page.mouse.up()
  await page.keyboard.up('Alt')
  const altAfter = await dump()
  assert.ok(Math.abs(altAfter[0].x - (altBefore[0].x + 37 / altZoom)) < 1e-6)
  assert.ok(!gridMultiple(altAfter[0].x), 'Alt drag skips grid snapping')
  assert.ok(Math.abs((altAfter[1].x - altBefore[1].x) - (altAfter[0].x - altBefore[0].x)) < 1e-9)
  assert.ok(Math.abs((altAfter[1].y - altBefore[1].y) - (altAfter[0].y - altBefore[0].y)) < 1e-9)
  await page.locator('#snap-edges').click()
  await page.locator('#snap-centers').click()
  await page.locator('#snap-guides').click()

  await page.locator('#guide-add-v').click()
  assert.equal((await guidesOf()).length, 1)
  assert.equal((await guidesOf())[0].orientation, 'vertical')
  assert.equal((await selectionSet()).items.length, 0)
  assert.equal(await page.locator('#properties-title').innerText(), 'Guide')
  const guideX = (await guidesOf())[0].position
  const boxHeight = (await canvasBox()).height
  let guidePoint = null
  for (const candidateY of [-100, -200, -300, -500, 2000, 2500]) {
    const p = await page.evaluate(([gx, yy]) => window.__ledmap.projectToPx({ x: gx, y: yy }), [guideX, candidateY])
    if (p.y > 10 && p.y < boxHeight - 10) {
      guidePoint = p
      break
    }
  }
  assert.ok(guidePoint, 'found an on-screen empty point on the guide')
  const guideZoom = (await camera()).zoom
  await page.mouse.move(box.x + guidePoint.x, box.y + guidePoint.y)
  await page.mouse.down()
  await page.mouse.move(box.x + guidePoint.x + 50, box.y + guidePoint.y, { steps: 5 })
  await page.mouse.up()
  assert.ok(Math.abs((await guidesOf())[0].position - (guideX + 50 / guideZoom)) < 1)
  await page.locator('input[aria-label="Guide Locked"]').check()
  assert.equal((await guidesOf())[0].locked, true)
  const lockedGuideAt = (await guidesOf())[0].position
  await page.keyboard.press('Escape')
  await page.mouse.move(box.x + guidePoint.x + 50, box.y + guidePoint.y)
  await page.mouse.down()
  await page.mouse.move(box.x + guidePoint.x + 80, box.y + guidePoint.y, { steps: 3 })
  await page.mouse.up()
  assert.equal((await guidesOf())[0].position, lockedGuideAt, 'locked guide is not draggable')
  await page.keyboard.press('Delete')
  assert.equal((await guidesOf()).length, 1, 'locked guide is not deletable')
  await page.locator('input[aria-label="Guide Locked"]').uncheck()
  await page.keyboard.press('Delete')
  assert.equal((await guidesOf()).length, 0)

  await page.locator('#project-tree [role="treeitem"]').filter({ hasText: 'Screen 1' }).click()
  await page.locator('#project-tree [role="treeitem"]').filter({ hasText: 'Screen 2' }).click({ modifiers: ['Control'] })
  await page.locator('#project-tree [role="treeitem"]').filter({ hasText: 'Screen 3' }).click({ modifiers: ['Control'] })
  await page.locator('#align-select').selectOption('left')
  const aligned = await dump()
  assert.ok(aligned[0].x === aligned[1].x && aligned[1].x === aligned[2].x)
  await page.locator('#distribute-select').selectOption('horizontal')
  const distributed = await dump()
  const atX = id => distributed.find(s => s.id === id)
  const distIds = ['screen-1', 'screen-2', 'screen-3']
  const dgaps = [0, 1].map(i => atX(distIds[i + 1]).x - (atX(distIds[i]).x + atX(distIds[i]).width))
  assert.ok(Math.abs(dgaps[0] - dgaps[1]) < 1e-6)

  await page.locator('#project-tree [role="treeitem"]').filter({ hasText: 'Screen 1' }).click()
  await page.locator('input[aria-label="Screen Locked"]').check()
  await page.locator('#project-tree [role="treeitem"]').filter({ hasText: 'Screen 2' }).click({ modifiers: ['Control'] })
  await page.locator('#project-tree [role="treeitem"]').filter({ hasText: 'Screen 3' }).click({ modifiers: ['Control'] })
  const blockedBefore = await dump()
  await page.locator('#align-select').selectOption('left')
  assert.deepEqual(await dump(), blockedBefore, 'align with a locked member changes nothing')
  await page.locator('#distribute-select').selectOption('horizontal')
  assert.deepEqual(await dump(), blockedBefore, 'distribute with a locked member changes nothing')
  await page.locator('#project-tree [role="treeitem"]').filter({ hasText: 'Screen 1' }).click()
  await page.locator('input[aria-label="Screen Locked"]').uncheck()

  await page.locator('#guide-add-v').click()
  assert.equal(await page.locator('#properties-title').innerText(), 'Guide')
  assert.equal(await page.locator('#selection-chip').innerText(), 'Guide selected')
  await page.locator('#project-tree [role="treeitem"]').filter({ hasText: 'Screen 1' }).click()
  assert.equal(await page.locator('#properties-title').innerText(), 'Screen')
  assert.equal(await page.locator('#selection-chip').innerText(), 'Screen 1 selected')
  assert.equal((await selectionSet()).items.length, 1)
  await page.locator('#guide-add-v').click()
  assert.equal(await page.locator('#properties-title').innerText(), 'Guide')
  assert.equal((await selectionSet()).items.length, 0)
  await page.locator('button[aria-label="Delete Guide"]').click()
  assert.equal((await guidesOf()).length, 1)
  await page.locator('#project-tree [role="treeitem"]').filter({ hasText: 'Screen 1' }).click()
  assert.equal(await page.locator('#properties-title').innerText(), 'Screen')

  await page.locator('#project-tree [role="treeitem"]').filter({ hasText: 'Grid' }).first().click()
  assert.equal(await page.locator('#properties-title').innerText(), 'Cabinet Grid')
  const gridDeleteBefore = await dump()
  await page.keyboard.press('Delete')
  assert.deepEqual(await dump(), gridDeleteBefore, 'grid selection Delete is a no-op')

  await page.locator('#project-tree [role="treeitem"]').filter({ hasText: 'Screen 1' }).click()
  await page.locator('#toggle-mode').click()
  await page.locator('#fit-project').click()
  const firstScreen = (await dump()).find(s => s.id === 'screen-1')
  const restScreens = (await dump()).filter(s => s.id !== 'screen-1')
  const uncovered = firstScreen.cabinets.find(c => {
    const px = firstScreen.x + (c.column + 0.5) * (firstScreen.width / firstScreen.columns)
    const py = firstScreen.y + (c.row + 0.5) * (firstScreen.height / firstScreen.rows)
    return !restScreens.some(o => px >= o.x && px < o.x + o.width && py >= o.y && py < o.y + o.height)
  })
  assert.ok(uncovered, 'found a cabinet cell of screen-1 not covered by other screens')
  const cabinetProbe = await page.evaluate(([x, y]) => window.__ledmap.projectToPx({ x, y }), [
    firstScreen.x + (uncovered.column + 0.5) * (firstScreen.width / firstScreen.columns),
    firstScreen.y + (uncovered.row + 0.5) * (firstScreen.height / firstScreen.rows),
  ])
  await page.keyboard.press('Escape')
  await page.mouse.click(box.x + cabinetProbe.x, box.y + cabinetProbe.y)
  assert.equal((await selection())?.type, 'cabinet')
  const cabinetDeleteBefore = await dump()
  await page.keyboard.press('Delete')
  assert.deepEqual(await dump(), cabinetDeleteBefore, 'cabinet-only Delete is a no-op')
  assert.equal((await selection())?.type, 'cabinet')
  await page.locator('#toggle-mode').click()
  assert.equal(await viewMode(), 'all')

  await page.locator('#project-tree [role="treeitem"]').filter({ hasText: 'Screen 3' }).click()
  await page.locator('#project-tree [role="treeitem"]').filter({ hasText: 'Screen 2' }).click({ modifiers: ['Control'] })
  await page.keyboard.press('Delete')
  assert.deepEqual((await dump()).map(s => s.id), ['screen-1', 'screen-4'])
  assert.equal((await selectionSet()).items.length, 0)
  await page.locator('#toggle-mode').click()
  assert.equal(await viewMode(), 'active')
  assert.equal(await page.locator('#canvas-title').innerText(), 'Screen 1')
  await page.locator('#toggle-mode').click()
  assert.equal(await viewMode(), 'all')

  await page.screenshot({ path: `${output}/project-canvas.png` })
  assert.deepEqual(failures, [])
  console.log('Electron smoke passed: demo project, selection, properties edit, cabinet hit, drag, REF-001 safety, view modes, add screen, Escape clear.')
  console.log('Electron smoke passed: grid resize via Properties and handles, deferred commit, ID continuity, invalid input rejection.')
  console.log(`Screenshots: ${output}`)
} finally {
  await app.close()
}
